# Generated by Django 3.2.9 on 2022-07-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organizer', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=255)),
                ('wishlist', models.TextField(max_length=2042)),
                ('blacklist', models.TextField(max_length=2042)),
                ('address', models.TextField(default=None, max_length=2042)),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'nickname', 'email'],
            },
        ),
    ]
