# Generated by Django 3.2.9 on 2022-07-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='description_of_yourself',
            field=models.TextField(default=None, max_length=2042),
        ),
        migrations.AlterField(
            model_name='participant',
            name='blacklist',
            field=models.TextField(default=None, max_length=2042),
        ),
        migrations.AlterField(
            model_name='participant',
            name='wishlist',
            field=models.TextField(default=None, max_length=2042),
        ),
    ]
