# Generated by Django 3.2.9 on 2022-07-24 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('santapp', '0002_auto_20220724_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='santapp.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.CharField(default=None, max_length=2042),
        ),
        migrations.AlterField(
            model_name='participant',
            name='blacklist',
            field=models.CharField(default=None, max_length=2042),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nickname',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='wishlist',
            field=models.CharField(default=None, max_length=2042),
        ),
    ]
