# Generated by Django 3.2.9 on 2022-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santapp', '0003_auto_20220724_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default=None, max_length=32, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default=None, max_length=2042, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price_range',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(default=None, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_bought',
            field=models.BooleanField(default=False),
        ),
    ]
