# Generated by Django 3.2.9 on 2022-07-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santapp', '0004_auto_20220724_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
