# Generated by Django 3.2.9 on 2022-07-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santapp', '0008_remove_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
