# Generated by Django 3.2.9 on 2022-07-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santapp', '0012_alter_event_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default=None, max_length=2042, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_range',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
