# Generated by Django 3.2.9 on 2022-07-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santapp', '0013_auto_20220724_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exchange_list',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.CharField(default=None, max_length=2048),
        ),
        migrations.AlterField(
            model_name='participant',
            name='blacklist',
            field=models.CharField(default=None, max_length=2048),
        ),
        migrations.AlterField(
            model_name='participant',
            name='description_of_yourself',
            field=models.TextField(default=None, max_length=2048),
        ),
        migrations.AlterField(
            model_name='participant',
            name='wishlist',
            field=models.CharField(default=None, max_length=2048),
        ),
    ]
